_core:
  default_config_hash: 0LS6KiWDpzSx7lj-jcDW2kpN3bdP_7OzandLbf9Ax9s
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: false
  node_user_picture: false
logo:
  path: 'public://sec-logo.png'
  use_default: true
include_back_to_top: 1
threshold: '200'
smooth_scroll: 1
include_current_page_in_breadcrumb: 1
button_sizes: "c-button|Standard\r\nc-button.c-button--small|Small\r\nc-button.c-button--large|Large"
button_styles: "c-button|Primary\r\nc-button.c-button--secondary|Secondary\r\nc-button.c-button--outline|Outline\r\nc-button.c-button--danger|Danger"
